Attribute VB_Name = "xlwings_udfs"
'Autogenerated code by xlwings - changes will be lost with next import!
#Const App = "Microsoft Excel" 'Adjust when using outside of Excel
Function excelIO_UDF__loggerFinalize()
Attribute excelIO_UDF__loggerFinalize.VB_Description = "Python function 'excelIO_UDF__loggerFinalize' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF__loggerFinalize.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF__loggerFinalize = Py.CallUDF("interfaceExcel", "excelIO_UDF__loggerFinalize", Array(), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF__loggerFinalize = Py.CallUDF("interfaceExcel", "excelIO_UDF__loggerFinalize", Array())
        Exit Function
    #End If
failed:
    excelIO_UDF__loggerFinalize = Err.Description
End Function

Function excelIO_UDF_addFolderTree(topFolder, srcExcel, dstSheet, startRow, StartCol)
Attribute excelIO_UDF_addFolderTree.VB_Description = "Python function 'excelIO_UDF_addFolderTree' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_addFolderTree.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_addFolderTree = Py.CallUDF("interfaceExcel", "excelIO_UDF_addFolderTree", Array(topFolder, srcExcel, dstSheet, startRow, StartCol), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_addFolderTree = Py.CallUDF("interfaceExcel", "excelIO_UDF_addFolderTree", Array(topFolder, srcExcel, dstSheet, startRow, StartCol))
        Exit Function
    #End If
failed:
    excelIO_UDF_addFolderTree = Err.Description
End Function

Function excelIO_UDF_appendDataToLasRow(shtName, col, setVal)
Attribute excelIO_UDF_appendDataToLasRow.VB_Description = "Python function 'excelIO_UDF_appendDataToLasRow' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_appendDataToLasRow.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_appendDataToLasRow = Py.CallUDF("interfaceExcel", "excelIO_UDF_appendDataToLasRow", Array(shtName, col, setVal), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_appendDataToLasRow = Py.CallUDF("interfaceExcel", "excelIO_UDF_appendDataToLasRow", Array(shtName, col, setVal))
        Exit Function
    #End If
failed:
    excelIO_UDF_appendDataToLasRow = Err.Description
End Function

Function excelIO_UDF_clear_lst_expand_base()
Attribute excelIO_UDF_clear_lst_expand_base.VB_Description = "Python function 'excelIO_UDF_clear_lst_expand_base' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_clear_lst_expand_base.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_clear_lst_expand_base = Py.CallUDF("interfaceExcel", "excelIO_UDF_clear_lst_expand_base", Array(), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_clear_lst_expand_base = Py.CallUDF("interfaceExcel", "excelIO_UDF_clear_lst_expand_base", Array())
        Exit Function
    #End If
failed:
    excelIO_UDF_clear_lst_expand_base = Err.Description
End Function

Function excelIO_UDF_clear_lst_expand_target()
Attribute excelIO_UDF_clear_lst_expand_target.VB_Description = "Python function 'excelIO_UDF_clear_lst_expand_target' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_clear_lst_expand_target.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_clear_lst_expand_target = Py.CallUDF("interfaceExcel", "excelIO_UDF_clear_lst_expand_target", Array(), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_clear_lst_expand_target = Py.CallUDF("interfaceExcel", "excelIO_UDF_clear_lst_expand_target", Array())
        Exit Function
    #End If
failed:
    excelIO_UDF_clear_lst_expand_target = Err.Description
End Function

Function excelIO_UDF_df_fileCntByFolderItem(row, column)
Attribute excelIO_UDF_df_fileCntByFolderItem.VB_Description = "Python function 'excelIO_UDF_df_fileCntByFolderItem' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_df_fileCntByFolderItem.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_df_fileCntByFolderItem = Py.CallUDF("interfaceExcel", "excelIO_UDF_df_fileCntByFolderItem", Array(row, column), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_df_fileCntByFolderItem = Py.CallUDF("interfaceExcel", "excelIO_UDF_df_fileCntByFolderItem", Array(row, column))
        Exit Function
    #End If
failed:
    excelIO_UDF_df_fileCntByFolderItem = Err.Description
End Function

Function excelIO_UDF_expandFolderTree(Optional srcExcel, Optional srcSheet, Optional dstSheet, Optional startRow, Optional StartCol)
Attribute excelIO_UDF_expandFolderTree.VB_Description = "Python function 'excelIO_UDF_expandFolderTree' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_expandFolderTree.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_expandFolderTree = Py.CallUDF("interfaceExcel", "excelIO_UDF_expandFolderTree", Array(srcExcel, srcSheet, dstSheet, startRow, StartCol), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_expandFolderTree = Py.CallUDF("interfaceExcel", "excelIO_UDF_expandFolderTree", Array(srcExcel, srcSheet, dstSheet, startRow, StartCol))
        Exit Function
    #End If
failed:
    excelIO_UDF_expandFolderTree = Err.Description
End Function

Function excelIO_UDF_filrOpen_with_sakuraEditor(Optional topFolder, Optional workTextFile)
Attribute excelIO_UDF_filrOpen_with_sakuraEditor.VB_Description = "Python function 'excelIO_UDF_filrOpen_with_sakuraEditor' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_filrOpen_with_sakuraEditor.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_filrOpen_with_sakuraEditor = Py.CallUDF("interfaceExcel", "excelIO_UDF_filrOpen_with_sakuraEditor", Array(topFolder, workTextFile), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_filrOpen_with_sakuraEditor = Py.CallUDF("interfaceExcel", "excelIO_UDF_filrOpen_with_sakuraEditor", Array(topFolder, workTextFile))
        Exit Function
    #End If
failed:
    excelIO_UDF_filrOpen_with_sakuraEditor = Err.Description
End Function

Function excelIO_UDF_generateFileCntByFolderList(Optional srcSheet, Optional topRow, Optional rowCount, Optional fileCntUpperLimit)
Attribute excelIO_UDF_generateFileCntByFolderList.VB_Description = "Python function 'excelIO_UDF_generateFileCntByFolderList' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_generateFileCntByFolderList.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_generateFileCntByFolderList = Py.CallUDF("interfaceExcel", "excelIO_UDF_generateFileCntByFolderList", Array(srcSheet, topRow, rowCount, fileCntUpperLimit), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_generateFileCntByFolderList = Py.CallUDF("interfaceExcel", "excelIO_UDF_generateFileCntByFolderList", Array(srcSheet, topRow, rowCount, fileCntUpperLimit))
        Exit Function
    #End If
failed:
    excelIO_UDF_generateFileCntByFolderList = Err.Description
End Function

Function excelIO_UDF_generateNewFileFullPath(oldFullPath, newEndFolderName)
Attribute excelIO_UDF_generateNewFileFullPath.VB_Description = "Python function 'excelIO_UDF_generateNewFileFullPath' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_generateNewFileFullPath.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_generateNewFileFullPath = Py.CallUDF("interfaceExcel", "excelIO_UDF_generateNewFileFullPath", Array(oldFullPath, newEndFolderName), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_generateNewFileFullPath = Py.CallUDF("interfaceExcel", "excelIO_UDF_generateNewFileFullPath", Array(oldFullPath, newEndFolderName))
        Exit Function
    #End If
failed:
    excelIO_UDF_generateNewFileFullPath = Err.Description
End Function

Function excelIO_UDF_getDestHyperLinkRow(Optional srcExcel, Optional srcSheet, Optional desstFolderNane)
Attribute excelIO_UDF_getDestHyperLinkRow.VB_Description = "Python function 'excelIO_UDF_getDestHyperLinkRow' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_getDestHyperLinkRow.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_getDestHyperLinkRow = Py.CallUDF("interfaceExcel", "excelIO_UDF_getDestHyperLinkRow", Array(srcExcel, srcSheet, desstFolderNane), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_getDestHyperLinkRow = Py.CallUDF("interfaceExcel", "excelIO_UDF_getDestHyperLinkRow", Array(srcExcel, srcSheet, desstFolderNane))
        Exit Function
    #End If
failed:
    excelIO_UDF_getDestHyperLinkRow = Err.Description
End Function

Function excelIO_UDF_getExpandFolderTree()
Attribute excelIO_UDF_getExpandFolderTree.VB_Description = "Python function 'excelIO_UDF_getExpandFolderTree' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_getExpandFolderTree.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_getExpandFolderTree = Py.CallUDF("interfaceExcel", "excelIO_UDF_getExpandFolderTree", Array(), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_getExpandFolderTree = Py.CallUDF("interfaceExcel", "excelIO_UDF_getExpandFolderTree", Array())
        Exit Function
    #End If
failed:
    excelIO_UDF_getExpandFolderTree = Err.Description
End Function

Function excelIO_UDF_getFolderPermissions(Optional folderName)
Attribute excelIO_UDF_getFolderPermissions.VB_Description = "Python function 'excelIO_UDF_getFolderPermissions' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_getFolderPermissions.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_getFolderPermissions = Py.CallUDF("interfaceExcel", "excelIO_UDF_getFolderPermissions", Array(folderName), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_getFolderPermissions = Py.CallUDF("interfaceExcel", "excelIO_UDF_getFolderPermissions", Array(folderName))
        Exit Function
    #End If
failed:
    excelIO_UDF_getFolderPermissions = Err.Description
End Function

Function excelIO_UDF_getLatestFolder(targetFolder)
Attribute excelIO_UDF_getLatestFolder.VB_Description = "Python function 'excelIO_UDF_getLatestFolder' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_getLatestFolder.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_getLatestFolder = Py.CallUDF("interfaceExcel", "excelIO_UDF_getLatestFolder", Array(targetFolder), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_getLatestFolder = Py.CallUDF("interfaceExcel", "excelIO_UDF_getLatestFolder", Array(targetFolder))
        Exit Function
    #End If
failed:
    excelIO_UDF_getLatestFolder = Err.Description
End Function

Function excelIO_UDF_getSearchRootFolder()
Attribute excelIO_UDF_getSearchRootFolder.VB_Description = "Python function 'excelIO_UDF_getSearchRootFolder' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_getSearchRootFolder.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_getSearchRootFolder = Py.CallUDF("interfaceExcel", "excelIO_UDF_getSearchRootFolder", Array(), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_getSearchRootFolder = Py.CallUDF("interfaceExcel", "excelIO_UDF_getSearchRootFolder", Array())
        Exit Function
    #End If
failed:
    excelIO_UDF_getSearchRootFolder = Err.Description
End Function

Function excelIO_UDF_getWorkSheetToDataFrame(Optional srcExcel, Optional srcSheet, Optional row_colName)
Attribute excelIO_UDF_getWorkSheetToDataFrame.VB_Description = "Python function 'excelIO_UDF_getWorkSheetToDataFrame' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_getWorkSheetToDataFrame.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_getWorkSheetToDataFrame = Py.CallUDF("interfaceExcel", "excelIO_UDF_getWorkSheetToDataFrame", Array(srcExcel, srcSheet, row_colName), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_getWorkSheetToDataFrame = Py.CallUDF("interfaceExcel", "excelIO_UDF_getWorkSheetToDataFrame", Array(srcExcel, srcSheet, row_colName))
        Exit Function
    #End If
failed:
    excelIO_UDF_getWorkSheetToDataFrame = Err.Description
End Function

Function excelIO_UDF_get_expandFolderTree_status()
Attribute excelIO_UDF_get_expandFolderTree_status.VB_Description = "Python function 'excelIO_UDF_get_expandFolderTree_status' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_get_expandFolderTree_status.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_get_expandFolderTree_status = Py.CallUDF("interfaceExcel", "excelIO_UDF_get_expandFolderTree_status", Array(), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_get_expandFolderTree_status = Py.CallUDF("interfaceExcel", "excelIO_UDF_get_expandFolderTree_status", Array())
        Exit Function
    #End If
failed:
    excelIO_UDF_get_expandFolderTree_status = Err.Description
End Function

Function excelIO_UDF_initialize(srcExcel)
Attribute excelIO_UDF_initialize.VB_Description = "Python function 'excelIO_UDF_initialize' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_initialize.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_initialize = Py.CallUDF("interfaceExcel", "excelIO_UDF_initialize", Array(srcExcel), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_initialize = Py.CallUDF("interfaceExcel", "excelIO_UDF_initialize", Array(srcExcel))
        Exit Function
    #End If
failed:
    excelIO_UDF_initialize = Err.Description
End Function

Function excelIO_UDF_main(srcExcel)
Attribute excelIO_UDF_main.VB_Description = "Python function 'excelIO_UDF_main' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_main.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_main = Py.CallUDF("interfaceExcel", "excelIO_UDF_main", Array(srcExcel), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_main = Py.CallUDF("interfaceExcel", "excelIO_UDF_main", Array(srcExcel))
        Exit Function
    #End If
failed:
    excelIO_UDF_main = Err.Description
End Function

Function excelIO_UDF_outputBaseFullPath(index)
Attribute excelIO_UDF_outputBaseFullPath.VB_Description = "Python function 'excelIO_UDF_outputBaseFullPath' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_outputBaseFullPath.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_outputBaseFullPath = Py.CallUDF("interfaceExcel", "excelIO_UDF_outputBaseFullPath", Array(index), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_outputBaseFullPath = Py.CallUDF("interfaceExcel", "excelIO_UDF_outputBaseFullPath", Array(index))
        Exit Function
    #End If
failed:
    excelIO_UDF_outputBaseFullPath = Err.Description
End Function

Function excelIO_UDF_outputTargetFullPath(index)
Attribute excelIO_UDF_outputTargetFullPath.VB_Description = "Python function 'excelIO_UDF_outputTargetFullPath' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_outputTargetFullPath.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_outputTargetFullPath = Py.CallUDF("interfaceExcel", "excelIO_UDF_outputTargetFullPath", Array(index), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_outputTargetFullPath = Py.CallUDF("interfaceExcel", "excelIO_UDF_outputTargetFullPath", Array(index))
        Exit Function
    #End If
failed:
    excelIO_UDF_outputTargetFullPath = Err.Description
End Function

Function excelIO_UDF_search(Optional srcExcel, Optional sheetsList)
Attribute excelIO_UDF_search.VB_Description = "Python function 'excelIO_UDF_search' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_search.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_search = Py.CallUDF("interfaceExcel", "excelIO_UDF_search", Array(srcExcel, sheetsList), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_search = Py.CallUDF("interfaceExcel", "excelIO_UDF_search", Array(srcExcel, sheetsList))
        Exit Function
    #End If
failed:
    excelIO_UDF_search = Err.Description
End Function

Function excelIO_UDF_searchBranch(Optional srcExcel, Optional searchTopFolder, Optional resultSheet)
Attribute excelIO_UDF_searchBranch.VB_Description = "Python function 'excelIO_UDF_searchBranch' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_searchBranch.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_searchBranch = Py.CallUDF("interfaceExcel", "excelIO_UDF_searchBranch", Array(srcExcel, searchTopFolder, resultSheet), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_searchBranch = Py.CallUDF("interfaceExcel", "excelIO_UDF_searchBranch", Array(srcExcel, searchTopFolder, resultSheet))
        Exit Function
    #End If
failed:
    excelIO_UDF_searchBranch = Err.Description
End Function

Function excelIO_UDF_setBaseFullPath(item)
Attribute excelIO_UDF_setBaseFullPath.VB_Description = "Python function 'excelIO_UDF_setBaseFullPath' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_setBaseFullPath.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_setBaseFullPath = Py.CallUDF("interfaceExcel", "excelIO_UDF_setBaseFullPath", Array(item), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_setBaseFullPath = Py.CallUDF("interfaceExcel", "excelIO_UDF_setBaseFullPath", Array(item))
        Exit Function
    #End If
failed:
    excelIO_UDF_setBaseFullPath = Err.Description
End Function

Function excelIO_UDF_set_expandFolderTree_status(Optional status)
Attribute excelIO_UDF_set_expandFolderTree_status.VB_Description = "Python function 'excelIO_UDF_set_expandFolderTree_status' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_set_expandFolderTree_status.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_set_expandFolderTree_status = Py.CallUDF("interfaceExcel", "excelIO_UDF_set_expandFolderTree_status", Array(status), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_set_expandFolderTree_status = Py.CallUDF("interfaceExcel", "excelIO_UDF_set_expandFolderTree_status", Array(status))
        Exit Function
    #End If
failed:
    excelIO_UDF_set_expandFolderTree_status = Err.Description
End Function

Function excelIO_UDF_test(srcExcel, row, col)
Attribute excelIO_UDF_test.VB_Description = "Python function 'excelIO_UDF_test' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_test.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_test = Py.CallUDF("interfaceExcel", "excelIO_UDF_test", Array(srcExcel, row, col), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_test = Py.CallUDF("interfaceExcel", "excelIO_UDF_test", Array(srcExcel, row, col))
        Exit Function
    #End If
failed:
    excelIO_UDF_test = Err.Description
End Function

Function excelIO_UDF_updataUserformCaption(Optional userformIndex, Optional msssage)
Attribute excelIO_UDF_updataUserformCaption.VB_Description = "Python function 'excelIO_UDF_updataUserformCaption' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute excelIO_UDF_updataUserformCaption.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        excelIO_UDF_updataUserformCaption = Py.CallUDF("interfaceExcel", "excelIO_UDF_updataUserformCaption", Array(userformIndex, msssage), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        excelIO_UDF_updataUserformCaption = Py.CallUDF("interfaceExcel", "excelIO_UDF_updataUserformCaption", Array(userformIndex, msssage))
        Exit Function
    #End If
failed:
    excelIO_UDF_updataUserformCaption = Err.Description
End Function

Function generateFullPath()
Attribute generateFullPath.VB_Description = "Python function 'generateFullPath' defined in 'd:\\git\\diff_foldertree_pythonproject\\interfaceExcel.py'."
Attribute generateFullPath.VB_ProcData.VB_Invoke_Func = " \n20"
    #If App = "Microsoft Excel" Then
        If TypeOf Application.Caller Is Range Then On Error GoTo failed
        generateFullPath = Py.CallUDF("interfaceExcel", "generateFullPath", Array(), ThisWorkbook, Application.Caller)
        Exit Function
    #Else
        generateFullPath = Py.CallUDF("interfaceExcel", "generateFullPath", Array())
        Exit Function
    #End If
failed:
    generateFullPath = Err.Description
End Function

